package com.ultimatelife.common.registry;

import com.ultimatelife.UltimateLife;
import net.minecraft.core.registries.Registries;
import net.minecraft.sounds.SoundEvent;
import net.minecraftforge.registries.DeferredRegister;

/**
 * Sound event registry.
 *
 * <p>Empty in Phase 1. Sound events are registered from here; their {@code sounds.json} definitions
 * are generated by {@code com.ultimatelife.common.data.client} providers once content exists.</p>
 */
public final class ModSounds {

    private ModSounds() {
    }

    public static final DeferredRegister<SoundEvent> SOUND_EVENTS =
            DeferredRegister.create(Registries.SOUND_EVENT, UltimateLife.MOD_ID);
}
